# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d534a5f916bcf4a8a1eee1acae3cb3dede916abe1a548c19a9d53ff4be0c26b47e801a41d22f1a929af22b26d479f8e3a8bd3f2342ffa4435ba2e895aa4ec712

test:
  secret_key_base: 3502f11a070ca1f91c6628b29338eaff65a828f92690912b288f2a050a919f5e09fbc278370f2b069fb640db996a9ee8001f08d8b6cdc9d0f6cc6235e71f319a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
